# YOUR NAME OR TITLE OF YOUR SITE
name: Bitcoin Beer

# YOUR BRAND/PERSONAL TAGLINE
tagline: Gli eventi informali in Italia per avvicinarsi a Bitcoin

# YOUR/BRAND IMAGE URL
Image_URL: https://github.com/Mendace/satoshibeer.org/blob/main/assets/tappo.png?raw=true

# CHANGE THE BACKGROUND IMAGE OF THE WEBSITE BY JUST ADDING THE IMAGE URL
Cover_Image: https://picsum.photos/1080?nocache=

# SOCIAL MEDIA
links:

  # IF YOU DON'T WANT TO USE ANY OF THE FOLLOWING, JUST LEAVE THE URL BLANK
    
     # TELEGRAM
  - Name: Telegram
    URL: http://telegram.me
    Username: BitcoinBeerHub
    Color: '#0088cc'
    Icon-Class: fab fa-telegram-plane

    # FACEBOOK
  - Name: Facebook
    URL: https://www.facebook.com
    Username: bitcoinbeeritalia/
    Color: '#3b5998'
    Icon-Class: fab fa-facebook

    # INSTAGRAM
  - Name: Instagram
    URL: https://www.instagram.com
    Username: bitcoinbeeritalia
    Color: '#DD2A7B'
    Icon-Class: fab fa-instagram

     # YOUTUBE
  - Name: YouTube
    URL: https://www.youtube.com/channel
    Username: UCmRZMKwLvcSj32EoZgp-V8w
    Color: '#ff0000'
    Icon-Class: fab fa-youtube

    # GITHUB
  - Name: GitHub
    URL: http://github.com
    Username: Mendace/bitcoinbeer.events
    Color: '#6e5494'
    Icon-Class: fab fa-github


    # EMAIL
  - Name: Email
    URL: 'mailto:prato@bitcoinbeer.events'
    Icon-Class: fas fa-envelope
    Color: '#e17055'
    Text_Color: '#ffffff'


    # CUSTOM LINK
  - Name: Site
    URL: https://bitcoinbeer.events
    Icon-Class: fas fa-link
    Color: '#ffb142'
    Text_Color: '#ffffff'

      # CUSTOM LINK
  - Name: Nostr
    URL: https://l10n-main.snort-social.pages.dev/p/npub1rf8vy7m488zdmmevgkh74ene4aky9387nvaq6zx3gfkhyjgwnueqn4x24j
    Icon-Class: fas fa-link
    Color: '#6e5494'
    Text_Color: '#ffffff'


# YOU CAN REMOVE FOOTER COMPLETELY BY SIMPLY REMOVING EITHER THE YES OR REMOVING THE FOOTER STATEMENT BELOW COMPLETELY
footer: 'No'

# STOP EDITING HERE ---------- YOU'VE REACHED THE END OF THE CONFIGURATION

# Compress
compress_html:
  clippings: all

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Icon

# Base URL
# baseurl: /links

# Default Markdown Engine
markdown: kramdown
